routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/projects/create', 'ProjectsController@create')->name('create');
Route::post('/projects', 'ProjectsController@store');
Route::get('/projects/{project}','ProjectsController@show');
Route::get('/projects/{project}/delete','ProjectsController@destroy');
Route::get('/projects/{project}/revoke','ProjectsController@revoke');
Route::get('/projects/{project}/edit','ProjectsController@edit');
Route::post('/projects/{project}/complete','ProjectFeedbackController@store');
Route::get('/projects/{project}/skipcomplete','ProjectFeedbackController@skip');
Route::post('/projects/{project}/update','ProjectsController@update');
Route::get('/projects/{project}/writer/{writer}/profile','WritersController@profile');
Route::get('/projects/{project}/writer/{writer}','ProjectsController@hire');
Route::get('/demo', 'ProjectsController@demo');
Route::post('/projects/{project}/{user}/files', 'ProjectFilesController@store');
Route::post('/projects/{project}/chat/{user}', 'ProjectChatsController@store');
Route::get('/projects/{project}/{writer}/payment', 'ProjectPayController@index');
Route::post('/projects/{project}/{writer}/pay', 'ProjectPayController@store');
Route::get('/projects/{project}/turniton', 'ProjectPayController@turniton');

Route::get('/projects/{project}/writer/{writer}/accept','ProjectsController@accept');
Route::get('/projects/{project}/writer/{writer}/decline','ProjectsController@decline');
Route::get('/projects/{project}/{writer}/cancelrequest','ProjectsController@cancelRequest');

Route::get('/files/{file}/{project}/delete','ProjectFilesController@destroy');
Route::get('/files','FilesController@index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/user/{user}/updateprofile', 'ProfileController@updateProfile');
Route::post('/user/{user}/changepassword', 'ProfileController@updatePassword');
Route::get('/user/{user}/tours', 'ProfileController@tours');

Route::post('/profile/avatar', 'ProfileController@updateAvatar');


Route::get('/writer/register', 'WriterregisterController@index');
Route::get('/writer/document', 'WriterDocumentsController@index');
Route::post('/writer/document', 'WriterDocumentsController@store');
Route::post('/writer', 'WriterregisterController@store');
Route::get('/writer', 'WriterloginController@index');
Route::get('/writer/login', 'WriterloginController@index');
Route::get('/writer/test', 'WriterquizController@index');
Route::post('/writer/test', 'WriterquizController@store');

Route::get('/writer/notverify', 'WritersController@notverify');
Route::get('/writer/project', 'WriterprojectController@index');

Route::get('/writer/project/details', 'WriterprojectController@show');

Route::get('/writer/profile', 'WriterprofileController@index');
Route::get('/writer/security', 'WriterprofileController@security');
// Route::get('/writer/wallet', 'WriterprofileController@wallet');
Route::get('/wallet', 'WriterprofileController@wallet');

Route::get('/profile/edit', 'ProfileController@view');
Route::get('/profile', 'ProfileController@index');
Route::get('/profile/feedback', 'WriterprofileController@feedback');
Route::get('/profile/security', 'ProfileController@security');
Route::get('/profile/availability', 'ProfileController@availability');
Route::post('/profile/availability', 'ProfileController@saveavailability');
Route::get('/feedback', 'ProfileController@feedback');
// Route::get('/wallet','ProfileController@wallet');

Route::get('/order', 'OrderController@index');
Route::get('/order/show', 'OrderController@show');



Route::get('/admin/login', 'Backend\BackendLoginController@index');
Route::post('/admin/login', 'Backend\BackendLoginController@login');
Route::get('/admin/logout', 'Backend\BackendLoginController@logout');

Route::get('/admin', 'Backend\BackendDashboardController@index');
Route::get('/admin/users', 'Backend\BackendUsersController@index');
Route::get('/admin/users/{user}', 'Backend\BackendUsersController@show');
Route::get('/admin/users/{user}/delete', 'Backend\BackendUsersController@destroy');
Route::get('/admin/users/{user}/project/{project}', 'Backend\BackendUsersController@project');

Route::get('/admin/writers', 'Backend\BackendWritersController@index');
Route::get('/admin/writers/pending', 'Backend\BackendWritersController@pending');
Route::get('/admin/writers/verified', 'Backend\BackendWritersController@verified');
Route::get('/admin/writers/unverified', 'Backend\BackendWritersController@unverified');
Route::get('/admin/writers/{user}/project/{project}', 'Backend\BackendWritersController@project');
Route::get('/admin/writers/{writer}', 'Backend\BackendWritersController@show');
Route::get('/admin/writers/{writer}/delete', 'Backend\BackendWritersController@destroy');
Route::post('/admin/writers/{writer}/verify', 'Backend\BackendWritersController@verify');
Route::get('/admin/writers/{writer}/unverify', 'Backend\BackendWritersController@unverify');
Route::post('/admin/writers/{writer}/rate', 'Backend\BackendWritersController@rate');

Route::get('/admin/payments', 'Backend\BackendPaymentsController@index');
Route::get('/admin/projects/{project}/pay', 'Backend\BackendPaymentsController@store');
Route::resource('/admin/durations', 'Backend\BackendDurationController');


Route::get('/admin/verification/pending', 'Backend\BackendVerificationsController@pending');
Route::get('/admin/verification/writer/{writer}', 'Backend\BackendVerificationsController@writer');

Route::get('/admin/projects', 'Backend\BackendProjectsController@index');
Route::get('/admin/projects/{project}', 'Backend\BackendProjectsController@show');
Route::get('/admin/projects/{project}/delete', 'Backend\BackendProjectsController@destroy');

Route::get('/admin/subjects', 'Backend\BackendSubjectsController@index');
Route::post('/admin/subjects', 'Backend\BackendSubjectsController@store');
Route::post('/admin/subjects/{subject}/update', 'Backend\BackendSubjectsController@update');
Route::get('/admin/subjects/{subject}/delete', 'Backend\BackendSubjectsController@destroy');

Route::get('/admin/papertypes', 'Backend\BackendPaperTypeController@index');
Route::post('/admin/papertypes', 'Backend\BackendPaperTypeController@store');
Route::post('/admin/papertypes/{papertype}/update', 'Backend\BackendPaperTypeController@update');
Route::get('/admin/papertypes/{papertype}/delete', 'Backend\BackendPaperTypeController@destroy');

Route::get('/admin/citations', 'Backend\BackendCitationsController@index');
Route::post('/admin/citations', 'Backend\BackendCitationsController@store');
Route::post('/admin/citations/{citation}/update', 'Backend\BackendCitationsController@update');
Route::get('/admin/citations/{citation}/delete', 'Backend\BackendCitationsController@destroy');

Route::get('/admin/files', 'Backend\BackendFilesController@index');
Route::post('/admin/files/{file}/verify', 'Backend\BackendFilesController@verify');
Route::post('/admin/files/{file}/unverify', 'Backend\BackendFilesController@unverify');


Route::get('/admin/sociallinks', 'Backend\BackendSocialLinksController@index');
Route::post('/admin/sociallinks', 'Backend\BackendSocialLinksController@store');
Route::get('/admin/settings', 'Backend\BackendSettingsController@index');
Route::post('/admin/settings', 'Backend\BackendSettingsController@store');

Route::get('/admin/database', 'Backend\BackendDatabaseController@index');
Route::post('/admin/database/clear', 'Backend\BackendDatabaseController@clear');
Route::post('/admin/database/subjects/clear', 'Backend\BackendDatabaseController@subjectsClear');
Route::post('/admin/database/papertype/clear', 'Backend\BackendDatabaseController@papertypeClear');
Route::post('/admin/database/citation/clear', 'Backend\BackendDatabaseController@citationClear');



Route::get('/maildemo', 'ProjectsController@maildemo');


Route::view('/terms-of-conditions', 'legals.terms');
Route::view('/privacy-policy', 'legals.privacy');
Route::view('/contact-us', 'legals.contact');
Route::post('/contact', 'ContactController@send');

app/Models/Project.php
<?php

namespace App\Models;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['writer_id','type','topic','subject','pages_count','deadline_date','deadline_time','type_of_service','writing_quality','citations_count','citation_format','instructions','additional_instructions','files', 'completed', 'status', 'payment_status', 'admin_payment_status', 'truniton'];

    protected $appends = ['file_url', 'ongoing_file_url', 'feedback'];

    protected $casts = [
        'files' => 'array',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function writer()
    {
        return $this->belongsTo(User::class, 'writer_id');
    }
    public function getIsOwnedAttribute()
    {
        return $this->user_id == auth()->id() ? 1 : 0;
    }

    public function getTimestampAttribute()
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d h:i a', $this->deadline_date . ' ' . $this->deadline_time);
    }


    public function getProjectStatusAttribute()
    {
        if($this->writer_id == 0)
        {
            return 'Posted';
        }
        elseif($this->status == 4) {
            return 'Completed';
        }
        elseif($this->status == 2) {
            return 'Pay';
        }
        elseif($this->status == 3) {
            return 'Ongoing';
        }
        elseif($this->user_id == auth()->id() && $this->status == 1) {
            return 'Requested';
        }
        elseif($this->writer_id == auth()->id() && $this->status == 1) {
            return 'New Request';
        }
    }

    public function projectfiles()
    {
        if(auth()->id() == $this->writer_id){
            return $this->hasMany(ProjectFile::class)->latest();
        }else{
            return $this->hasMany(ProjectFile::class)->where('is_verify', 1)->latest();
        }
    }

    public function projectAdminFiles()
    {
        return $this->hasMany(ProjectFile::class)->where('user_id', $this->writer_id)->latest();
    }

    public function projectWriterFiles()
    {
        if(auth()->id() == $this->writer_id){
            return $this->hasMany(ProjectFile::class)->where('user_id', $this->writer_id)->latest();
        }else{
            return $this->hasMany(ProjectFile::class)->where('user_id', $this->writer_id)->where('is_verify', 1)->latest();
        }
    }

    public function projectUserFiles()
    {
        return $this->hasMany(ProjectFile::class)->where('user_id', $this->user_id)->where('is_verify', 1)->latest();
    }

    /*public function getOwnerUserNameAttribute()
    {
        return $this->user->username;
    }

    public function getWriterUserNameAttribute()
    {
        return $this->writer->username;
    }*/

    public function getFileUrlAttribute()
    {
        $files =[];
        if(isset($this->files)){
            foreach ($this->files as $key => $file) {
                $files[$key] = \Storage::url($file);
            }
        }
        return $files;
    }
    public function getOngoingFileUrlAttribute()
    {
        $files = $this->projectfiles;
    }

    public function chats()
    {
        return $this->hasMany(ProjectChat::class);
    }

    public function feedback()
    {
        return $this->hasOne(ProjectFeedback::class);
    }

    public function getFeedbackAttribute()
    {
        return $this->hasOne(ProjectFeedback::class)->first();
    }

}

resources/views/home.blade.php
@extends('layouts.app')
@section('styles')
<style type="text/css">
#wizard .steps a{
    pointer-events: none;
}
</style>
@endsection

@section('content')

    <div class="my-md-5 my-sm-0">

            <div class="headline d-flex justify-content-between align-items-cente hidden-on-mobile">
                <h3 class="d-inline-block">Projects</h3>
                @if(!auth()->user()->be_writer)
                 <a href="#postProjectModal" data-toggle="modal" id="tour-step-1" class="btn btn-secondary">Post a project</a>
                @endif
            </div>
    @section('heading', 'Projects')

        @if(count($projects))
        <div class="row user-project-details project-list">
            @foreach($projects as $project)
            <div class="col-sm-4 project-card">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="brows-job-type">
                            <span class="full-time {{ $project->project_status == 'New Request' ? 'newrequest' : $project->project_status }} text-capitalize">{{ $project->project_status }}</span>
                        </div>
                        {{-- <span class="tg-themetag tg-featuretag">{{$project->writing_quality}}</span> --}}
                        <!-- <div class="brows-job-company-img mt-3">
                            <img src="/img/com-2.jpg" class="img-responsive" alt="">
                        </div> -->
                        <div class="project-list-detalis">
                            <h4>{{str_limit($project->topic,15)}} </h4>

                            <p class="mt-2">{{str_limit($project->instructions, 75)}}</p>
                            <div class="d-flex justify-content-between align-items-center pt-2">
                            <a href="/projects/{{$project->id}}" class="btn btn-sm btn-outline-success">Manage</a>
                            @if(!auth()->user()->be_writer)
                            <div>
                                @if(!$project->completed)
                                <a href="/projects/{{$project->id}}/edit" class="btn btn-sm btn-light text-muted"><i class="fa fa-pencil"></i></a>
                                @endif
                                @if($project->status == 0 || $project->status == 1 || $project->status == 2)
                                <a href="/projects/{{$project->id}}/delete" onclick="return confirm('Are you sure, You want to delete this project?');" class="btn btn-sm btn-light text-muted"><i class="fa fa-trash"></i></a>
                                @endif
                            </div>
                            @endif
                            </div>
                        </div>
                    </div>
                    <ul class="grid-view-caption">
                        <li>
                            <div class="brows-job-location">
                                <p class="p-0" style="font-size: 12px;"><span><i class="fa fa-calendar-check-o" aria-hidden="true"></i>{{date('F d, Y', strtotime($project->deadline_date))}}</span></p>
                            </div>
                        </li>
                        <li>
                            <p style="font-size: 12px;"><span class="brows-job-location text-uppercase"><i class="fa fa-clock-o" aria-hidden="true"></i>{{$project->deadline_time}}</span></p>
                        </li>
                    </ul>
                </div>
            </div>
            @endforeach
        </div>
        @else
        @if(!auth()->user()->be_writer)
            <div class="empty-box row">
                <div class="col-md-12 text-center">
                     <h4 >You haven't posted any projects yet!</h4>
                     <p>Post a new project and choose an ideal writer on ProjectVala.</p>
                     <div class="my-md-5 my-sm-3 no-project-logo">
                        <img src="/img/typing.png" alt="project">
                     </div>
                     <div class="post-project-btn">
                        <a href="#postProjectModal" data-toggle="modal" class="btn btn-primary btn-lg mt-4">Let's Get Started</a>
                     </div>
                </div>
            </div>
        @else
        <div class="empty-box row">
                <div class="col-md-12 text-center">
                     <div class="no-project-logo">
                        <img src="/img/user/package.png" alt="project">
                     </div>
                     <h4 class="mt-3">You have no projects yet.</h4>
                     <div class="post-project-btn">
                        <!-- <a href="#" class="btn btn-secondary btn-lg mt-4">Post Project</a> -->
                     </div>
                </div>
            </div>
        @endif
        @endif


        {!! $projects->links() !!}
    </div>
@auth
 <nav class="bottom-nav">
            <a class="bottom-nav__action {{ request()->is('home') ? 'bottom-nav__action--active' : '' }}" href="/home">
                <!-- <svg class="bottom-nav__icon" viewBox="0 0 24 24">
                     <path d="M11,7V12.11L15.71,14.9L16.5,13.62L12.5,11.25V7M12.5,2C8.97,2 5.91,3.92 4.27,6.77L2,4.5V11H8.5L5.75,8.25C6.96,5.73 9.5,4 12.5,4A7.5,7.5 0 0,1 20,11.5A7.5,7.5 0 0,1 12.5,19C9.23,19 6.47,16.91 5.44,14H3.34C4.44,18.03 8.11,21 12.5,21C17.74,21 22,16.75 22,11.5A9.5,9.5 0 0,0 12.5,2Z"></path>
                </svg> -->
                <i class="fa fa-home"></i>
                <span class="bottom-nav__label">Home</span>
             </a>

            <a class="bottom-nav__action {{ request()->is('files') ? 'bottom-nav__action--active' : '' }}" href="/files">
                <!-- <svg class="bottom-nav__icon" viewBox="0 0 24 24">
                    <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
                </svg> -->
                <i class="fa fa-files-o"></i>
                <span class="bottom-nav__label">Files</span>
            </a>

            <a class="bottom-nav__action {{ request()->is('profile') ? 'bottom-nav__action--active' : '' }}" href="/profile">
                <!-- <svg class="bottom-nav__icon" viewBox="0 0 24 24">
                   <path d="M12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,12.5A1.5,1.5 0 0,1 10.5,11A1.5,1.5 0 0,1 12,9.5A1.5,1.5 0 0,1 13.5,11A1.5,1.5 0 0,1 12,12.5M12,7.2C9.9,7.2 8.2,8.9 8.2,11C8.2,14 12,17.5 12,17.5C12,17.5 15.8,14 15.8,11C15.8,8.9 14.1,7.2 12,7.2Z"></path>
                </svg> -->
                <i class="fa fa-cog"></i>
                <span class="bottom-nav__label">Settings</span>
            </a>
        </nav>
        @endauth

        @if(!auth()->user()->be_writer)
        <a href="#postProjectModal" data-toggle="modal" style="display: none;"  class="fab"> + </a>
        @endif
    @include('projects.create')
@endsection


@section('scripts')

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
  $(document).ready(function(){
 
    $('#deadline_date').datepicker({ 
    minDate: 0+2, 
    });


    $('#deadline_time').timepicker({
    'minTime': '00:00am',
    'maxTime': '06:00pm' 
    });

    
    
  });

</script>

    <script type="text/javascript">
        var tour = new Tour({
          steps: [
          {
            element: "#tour-step-1",
            title: "Post Project",
            content: "Click here to add new projects.",
            placement: "left",
            smartPlacement: false,
          },
          {
            element: "#tour-step-2",
            title: "Your Dashboard",
            content: "Click here for details of your projects.",
            placement: "right",
            smartPlacement: false,
          },
          {
            element: "#tour-step-3",
            title: "Files",
            content: "Click here to access files from writers.",
            placement: "right",
            smartPlacement: false,
          },
          {
            element: "#tour-step-3w",
            title: "Files",
            content: "Click here to access files from users.",
            placement: "right",
            smartPlacement: false,
          },
          {
            element: "#tour-step-4",
            title: "Settings",
            content: "Manage your profile and account settings.",
            placement: "right",
            smartPlacement: false,
          },
        ],
        backdrop: true,
        onEnd: function (tour) {
            axios.get('/user/{{auth()->id()}}/tours')
                .then(function (response) {
                })
                .catch(function (error) {
                });
        },
        });

        // Initialize the tour
        tour.init();

        // Start the tour
        @if(!auth()->user()->tour)
            localStorage.removeItem("tour_end");
            localStorage.removeItem("tour_current_step");
            tour.start();
        @endif

$(function () {
  var $sections = $('.form-section');

  function navigateTo(index) {
    // Mark the current section with the class 'current'
    $sections
      .removeClass('current')
      .eq(index)
        .addClass('current');
    // Show only the navigation buttons that make sense for the current section:
    /*$('.wizard-control[href="#previous"]').toggle(index > 0);
    */var atTheEnd = index >= $sections.length - 1;

    /*$('.wizard-control[href="#next"]').toggle(!atTheEnd);
    $('.wizard-control[href="#finish"]').toggle(atTheEnd);*/
  }

  function curIndex() {
    // Return the current index by looking at which section has the class 'current'
    return $sections.index($sections.filter('.current'));
  }

  // Previous button is easy, just go back
  $('.wizard-control [href="#previous"]').click(function() {
    navigateTo(curIndex() - 1);
  });

  // Next button goes forward iff current block validates
  $('.wizard-control[href="#next"]').click(function() {
    $('.frmPostAssignment').parsley().whenValidate({
      group: 'block-' + curIndex()
    }).done(function() {
        // console.log('clicked')
      $("#wizard").steps('next');
      //navigateTo(curIndex() + 1);
    });
  });

  // Prepare sections by setting the `data-parsley-group` attribute to 'block-0', 'block-1', etc.
  $sections.each(function(index, section) {
    $(section).find(':input').attr('data-parsley-group', 'block-' + index);
  });
  navigateTo(0); // Start at the beginning
});

$('#wizard').on('click', '.btn-postProject', function(){
    $(this).addClass('disabled');
    $(this).html('Creating project...')
});

$(function () {
var inputs = document.querySelectorAll( '#postProjectModal .uploadButton-input ' );
  Array.prototype.forEach.call( inputs, function( input )
  {
    var label = input.nextElementSibling.nextElementSibling,
    labelVal = label.innerHTML;

    input.addEventListener( 'change', function( e )
    {
      var fileName = '';

      fileName = e.target.value.split( '\\' ).pop();

      if( fileName )
        label.innerHTML = 'Selected File : <span class="filename">' + fileName + '</span>';
      else
        label.innerHTML = labelVal;
    });
  });
  });


    </script>
    


@endsection