routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/projects/create', 'ProjectsController@create')->name('create');
Route::post('/projects', 'ProjectsController@store');
Route::get('/projects/{project}','ProjectsController@show');
Route::get('/projects/{project}/delete','ProjectsController@destroy');
Route::get('/projects/{project}/revoke','ProjectsController@revoke');
Route::get('/projects/{project}/edit','ProjectsController@edit');
Route::post('/projects/{project}/complete','ProjectFeedbackController@store');
Route::get('/projects/{project}/skipcomplete','ProjectFeedbackController@skip');
Route::post('/projects/{project}/update','ProjectsController@update');
Route::get('/projects/{project}/writer/{writer}/profile','WritersController@profile');
Route::get('/projects/{project}/writer/{writer}','ProjectsController@hire');
Route::get('/demo', 'ProjectsController@demo');
Route::post('/projects/{project}/{user}/files', 'ProjectFilesController@store');
Route::post('/projects/{project}/chat/{user}', 'ProjectChatsController@store');
Route::get('/projects/{project}/{writer}/payment', 'ProjectPayController@index');
Route::post('/projects/{project}/{writer}/pay', 'ProjectPayController@store');
Route::get('/projects/{project}/turniton', 'ProjectPayController@turniton');

Route::get('/projects/{project}/writer/{writer}/accept','ProjectsController@accept');
Route::get('/projects/{project}/writer/{writer}/decline','ProjectsController@decline');
Route::get('/projects/{project}/{writer}/cancelrequest','ProjectsController@cancelRequest');

Route::get('/files/{file}/{project}/delete','ProjectFilesController@destroy');
Route::get('/files','FilesController@index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/user/{user}/updateprofile', 'ProfileController@updateProfile');
Route::post('/user/{user}/changepassword', 'ProfileController@updatePassword');
Route::get('/user/{user}/tours', 'ProfileController@tours');

Route::post('/profile/avatar', 'ProfileController@updateAvatar');


Route::get('/writer/register', 'WriterregisterController@index');
Route::get('/writer/document', 'WriterDocumentsController@index');
Route::post('/writer/document', 'WriterDocumentsController@store');
Route::post('/writer', 'WriterregisterController@store');
Route::get('/writer', 'WriterloginController@index');
Route::get('/writer/login', 'WriterloginController@index');
Route::get('/writer/test', 'WriterquizController@index');
Route::post('/writer/test', 'WriterquizController@store');

Route::get('/writer/notverify', 'WritersController@notverify');
Route::get('/writer/project', 'WriterprojectController@index');

Route::get('/writer/project/details', 'WriterprojectController@show');

Route::get('/writer/profile', 'WriterprofileController@index');
Route::get('/writer/security', 'WriterprofileController@security');
// Route::get('/writer/wallet', 'WriterprofileController@wallet');
Route::get('/wallet', 'WriterprofileController@wallet');

Route::get('/profile/edit', 'ProfileController@view');
Route::get('/profile', 'ProfileController@index');
Route::get('/profile/feedback', 'WriterprofileController@feedback');
Route::get('/profile/security', 'ProfileController@security');
Route::get('/profile/availability', 'ProfileController@availability');
Route::post('/profile/availability', 'ProfileController@saveavailability');
Route::get('/feedback', 'ProfileController@feedback');
// Route::get('/wallet','ProfileController@wallet');

Route::get('/order', 'OrderController@index');
Route::get('/order/show', 'OrderController@show');



Route::get('/admin/login', 'Backend\BackendLoginController@index');
Route::post('/admin/login', 'Backend\BackendLoginController@login');
Route::get('/admin/logout', 'Backend\BackendLoginController@logout');

Route::get('/admin', 'Backend\BackendDashboardController@index');
Route::get('/admin/users', 'Backend\BackendUsersController@index');
Route::get('/admin/users/{user}', 'Backend\BackendUsersController@show');
Route::get('/admin/users/{user}/delete', 'Backend\BackendUsersController@destroy');
Route::get('/admin/users/{user}/project/{project}', 'Backend\BackendUsersController@project');

Route::get('/admin/writers', 'Backend\BackendWritersController@index');
Route::get('/admin/writers/pending', 'Backend\BackendWritersController@pending');
Route::get('/admin/writers/verified', 'Backend\BackendWritersController@verified');
Route::get('/admin/writers/unverified', 'Backend\BackendWritersController@unverified');
Route::get('/admin/writers/{user}/project/{project}', 'Backend\BackendWritersController@project');
Route::get('/admin/writers/{writer}', 'Backend\BackendWritersController@show');
Route::get('/admin/writers/{writer}/delete', 'Backend\BackendWritersController@destroy');
Route::post('/admin/writers/{writer}/verify', 'Backend\BackendWritersController@verify');
Route::get('/admin/writers/{writer}/unverify', 'Backend\BackendWritersController@unverify');
Route::post('/admin/writers/{writer}/rate', 'Backend\BackendWritersController@rate');

Route::get('/admin/payments', 'Backend\BackendPaymentsController@index');
Route::get('/admin/projects/{project}/pay', 'Backend\BackendPaymentsController@store');
Route::resource('/admin/durations', 'Backend\BackendDurationController');


Route::get('/admin/verification/pending', 'Backend\BackendVerificationsController@pending');
Route::get('/admin/verification/writer/{writer}', 'Backend\BackendVerificationsController@writer');

Route::get('/admin/projects', 'Backend\BackendProjectsController@index');
Route::get('/admin/projects/{project}', 'Backend\BackendProjectsController@show');
Route::get('/admin/projects/{project}/delete', 'Backend\BackendProjectsController@destroy');

Route::get('/admin/subjects', 'Backend\BackendSubjectsController@index');
Route::post('/admin/subjects', 'Backend\BackendSubjectsController@store');
Route::post('/admin/subjects/{subject}/update', 'Backend\BackendSubjectsController@update');
Route::get('/admin/subjects/{subject}/delete', 'Backend\BackendSubjectsController@destroy');

Route::get('/admin/papertypes', 'Backend\BackendPaperTypeController@index');
Route::post('/admin/papertypes', 'Backend\BackendPaperTypeController@store');
Route::post('/admin/papertypes/{papertype}/update', 'Backend\BackendPaperTypeController@update');
Route::get('/admin/papertypes/{papertype}/delete', 'Backend\BackendPaperTypeController@destroy');

Route::get('/admin/citations', 'Backend\BackendCitationsController@index');
Route::post('/admin/citations', 'Backend\BackendCitationsController@store');
Route::post('/admin/citations/{citation}/update', 'Backend\BackendCitationsController@update');
Route::get('/admin/citations/{citation}/delete', 'Backend\BackendCitationsController@destroy');

Route::get('/admin/files', 'Backend\BackendFilesController@index');
Route::post('/admin/files/{file}/verify', 'Backend\BackendFilesController@verify');
Route::post('/admin/files/{file}/unverify', 'Backend\BackendFilesController@unverify');


Route::get('/admin/sociallinks', 'Backend\BackendSocialLinksController@index');
Route::post('/admin/sociallinks', 'Backend\BackendSocialLinksController@store');
Route::get('/admin/settings', 'Backend\BackendSettingsController@index');
Route::post('/admin/settings', 'Backend\BackendSettingsController@store');

Route::get('/admin/database', 'Backend\BackendDatabaseController@index');
Route::post('/admin/database/clear', 'Backend\BackendDatabaseController@clear');
Route::post('/admin/database/subjects/clear', 'Backend\BackendDatabaseController@subjectsClear');
Route::post('/admin/database/papertype/clear', 'Backend\BackendDatabaseController@papertypeClear');
Route::post('/admin/database/citation/clear', 'Backend\BackendDatabaseController@citationClear');



Route::get('/maildemo', 'ProjectsController@maildemo');


Route::view('/terms-of-conditions', 'legals.terms');
Route::view('/privacy-policy', 'legals.privacy');
Route::view('/contact-us', 'legals.contact');
Route::post('/contact', 'ContactController@send');

app/Models/Backend/Citation.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class Citation extends Model
{
    protected $fillable = ['name'];
}

app/Models/Backend/PaperType.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Model;

class PaperType extends Model
{
    protected $fillable = ['name'];
}

app/User.php
<?php

namespace App;

use App\Model\Wallet;
use App\Models\Project;
use App\Model\Assignment;
use App\Models\Availability;
use App\Models\WriterDocument;
use App\Models\Backend\Setting;
use App\Models\ProjectFeedback;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Password;
use App\Notifications\VerifyEmailNotification;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
// use Illuminate\Auth\Notifications\VerifyEmailNotification;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fname', 'lname', 'username', 'email', 'phone', 'password', 'be_writer', 'per_page_rate', 'subjects','score', 'quality', 'is_test', 'is_verify', 'profile_photo', 'is_available', 'api_token', 'commission_amt', 'tour'
    ];

    protected $appends = ['profile_photo_url', 'rating', 'email_verified'];

    protected $casts = ['per_page_rate' => 'array'];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function assignments()
    {
        return $this->hasMany(Assignment::class)->latest();
    }

    public function projects()
    {
        return $this->hasMany(Project::class)->latest();
    }

    public function writerProjects()
    {
        return $this->hasMany(Project::class, 'writer_id')->latest();
    }

    public function userProjects()
    {
        return $this->hasMany(Project::class, 'user_id')->latest();
    }

    /*public function getWriterRateAttribute()
    {
        return ($this->per_page_rate) + (getGlobalSettings() && isset(getGlobalSettings()->commission_amt) ? getGlobalSettings()->commission_amt : 0);
        // return number_format(($this->per_page_rate) + (getGlobalSettings() && isset(getGlobalSettings()->commission_amt) ? (getGlobalSettings()->commission_amt * $this->per_page_rate) /100 : 0), 2);

    }*/

    public function getCompletedProjectsCountAttribute()
    {
        if ($this->be_writer) {
            return $this->writerProjects()->where('completed', 1)->count();
        }else{
            return $this->userProjects()->where('completed', 1)->count();
        }
    }

    public function getOngoingProjectsCountAttribute()
    {
        if ($this->be_writer){
            return $this->writerProjects()->where('writer_id', '!=', 0)->where('completed', '!=', 1)->count();
        }else{
            return $this->userProjects()->where('writer_id', '!=', 0)->where('completed', '!=', 1)->count();
        }
    }

    public function project_rate(Project $project)
    {
        $diff = $project->timestamp->diffInHours(\Carbon\Carbon::now());
        $rateArray = explode(',', $this->per_page_rate);
        $rate = $rateArray[rateIndex($diff)];
        return $rate + ($rate * ((isset($this->commission_amt) ? $this->commission_amt : 0)/100));
    }

    public function project_rate_for_writer(Project $project)
    {
        $diff = $project->timestamp->diffInHours(\Carbon\Carbon::now());
        $rateArray = explode(',', $this->per_page_rate);
        $rate = $rateArray[rateIndex($diff)];
        return $rate;
    }

    public function wallet()
    {
        return $this->hasOne(Wallet::class);
    }

    public function feedback()
    {
        return $this->hasMany(ProjectFeedback::class, 'writer_id');
    }

    public function writerDocument()
    {
        return $this->hasOne(WriterDocument::class);
    }

    public function availability()
    {
        return $this->hasOne(Availability::class);
    }

    public function initWallet()
    {
        return isset($this->wallet) ? $this->wallet : $this->wallet()->create(['balance' => 0]);
    }

    public function getRatingAttribute()
    {

        return count($this->feedback) ? $this->feedback()->sum('rating') / count($this->feedback) : '3.0';
    }


     public function isWriterAvailable(Project $project)
    {
         if(isset($this->availability)){

            $availability = str_replace(' ', '', $this->availability->available_dates);
            $dates = explode(',' , $availability);
            if (in_array($project->deadline_date, $dates)) {
                return true;
            } else {
                return false;
            }
        }

        return false;
    }

    public function getWriterIsAvailableAttribute()
    {
        if(isset($this->availability)){

            $availability = str_replace(' ', '', $this->availability->available_dates);
            $dates = explode(',' , $availability);
            if (in_array(date('Y-m-d'), $dates)) {
                return true;
            } else {
                return false;
            }
        }

        return false;
    }

    public function getHistoryAttribute()
    {
        return count($this->writerProjects) ? $this->writerProjects()->where('user_id', auth()->id())->get() : [];
    }

    public function getWriterHistoryAttribute()
    {
        return count($this->userProjects) ? $this->userProjects()->where('writer_id', auth()->id())->get() : [];
    }

    public function getApiHistoryAttribute()
    {
        return count($this->writerProjects) ? $this->writerProjects()->where('user_id', auth()->id())->select('id','topic', 'created_at', 'deadline_date', 'deadline_time', 'status', 'completed')->get() : [];
    }

    public function getApiWriterHistoryAttribute()
    {
        return count($this->userProjects) ? $this->userProjects()->where('writer_id', auth()->id())->select('id','topic', 'created_at', 'deadline_date', 'deadline_time', 'status', 'completed')->get() : [];
    }

    public function getFullnameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function getEmailVerifiedAttribute()
    {
        return isset($this->email_verified_at) ? 1 : 0;
    }

    public function getProfilePhotoUrlAttribute()
    {
        return $this->profile_photo ? \Storage::url($this->profile_photo) : null;
    }

    public function generateToken()
    {
        if($this->api_token == null) {

          $token = substr(Password::getRepository()->createNewToken(), 0, 58);
          if (User::where('api_token', '=', $token)->exists()) {
                //Model Found -- call self.
                self::generate($length, $modelClass, $fieldName);
            } else {
                $this->api_token = $token;
                $this->save();
            }

       }

    }


    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmailNotification($this));
    }
}

app/Http/Controllers/Backend/BackendCitationsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Backend\Citation;
use App\Http\Controllers\Controller;

class BackendCitationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin_login');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $citations = Citation::paginate(10);
        return view('backend.citations.index', compact('citations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Citation::create($request->all());
        flash('Citation added successfully!');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Citation $citation)
    {
        $citation->update($request->all());
        flash('Citation updated successfully!');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Citation $citation)
    {
        $citation->delete();
        flash('Citation deleted successfully!');
        return back();
    }
}

resources/views/backend/verifications/pending.blade.php
@extends('layouts.backend')

@section('content')
<div class="my-md-5 my-sm-0">
    <div class="headline d-flex justify-content-between align-items-cente hidden-on-mobile">
        <h3 class="d-inline-block">Writers Pending Verifications</h3>
    </div>
    <div class="clearfix"></div>
    <div class="mt-4">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Sr.No.</th>
                    <th>Writer Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($writers as $key => $writer)
                <tr>
                    <td>{{$key + 1}}</td>
                    <td>{{$writer->fullname}}</td>
                    <td>{{$writer->email}}</td>
                    <td>{{$writer->phone}}</td>
                    <td>
                        <a href="/admin/verification/writer/{{$writer->id}}" class="btn btn-secondary btn-sm">View</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $writers->links() }}
    </div>
</div>
@endsection

resources/views/backend/verifications/writer.blade.php
@extends('layouts.backend')

@section('content')
<div class="my-md-5 my-sm-0">
    <div class="headline d-flex justify-content-between align-items-cente hidden-on-mobile">
        <h3 class="d-inline-block">Writer Profile</h3>
        <a href="/admin/verification/pending" class="btn  btn-default bg-secondary text-white float-right">Back</a>
    </div>

    <section class="profile-section profile-wallet-section my-5">
        <div class="d-flex border rounded justify-content-between align-center p-3 mb-3">
            <div class="">
                @if(isset($writer->profile_photo) && $writer->profile_photo)
                <img src="{{Storage::url($writer->profile_photo)}}" class="img-responsive rounded-circle mb-2" style="width:100px; height: 100px; vertical-align: initial;border: 2px solid rgb(117, 117, 117);">
                @else
                <img src="{{asset('img/user.png')}}" class="mb-2 img-thumbnail rounded-circle"  style="width:100px; height: 100px;">
                @endif
            </div>
            <div class="pl-4" style="flex: 1">
                <p class="mb-2"><b>{{$writer->fullname}}</b></p>
                <p class="mb-2"><i class="fa fa-envelope"></i> {{$writer->email}}</p>
                <p class="mb-2"><i class="fa fa-phone"></i> {{$writer->phone}}</p>
                <!-- <p class="mb-2 badge badge-success py-2 px-4">Test Score : {{$writer->score}}</p> -->
                <p class="mb-2 badge badge-success py-2 px-4">{{$writer->quality}}</p>
            </div>
            <div class="">
                <div class="">
                    @if($writer->is_verify == 1)
                    <a href="javascript:;" class="btn btn-success disabled"><i class="fa fa-check"></i> Verified</a>
                    <a href="/admin/writers/{{$writer->id}}/unverify" class="btn btn-danger">Unverify</a>
                    @elseif($writer->is_verify == 2)
                    <a href="#verifyModal" data-toggle="modal" class="btn btn-success">Verify</a>
                    <a href="javascript:;" class="btn btn-danger disabled"><i class="fa fa-times"></i> Unverified</a>
                    @else
                    <a href="#verifyModal" data-toggle="modal" class="btn btn-success">Verify</a>
                    <a href="/admin/writers/{{$writer->id}}/unverify" class="btn btn-danger">Unverify</a>
                    @endif
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->aadhar_card) && $writer->writerDocument->aadhar_card)
                    <div class="col-sm-3">
                        <div class="custom-file-upload">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->aadhar_card)}}" class="attachment-title">Aadhar Card</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->aadhar_card)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->pan_card) && $writer->writerDocument->pan_card)
                    <div class="col-sm-3">
                        <div class="custom-file-upload">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->pan_card)}}" class="attachment-title">Pan Card</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->pan_card)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->tenth_marksheet) && $writer->writerDocument->tenth_marksheet)
                    <div class="col-sm-3">
                        <div class="custom-file-upload">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->tenth_marksheet)}}" class="attachment-title">10<sup>th</sup> Marksheet</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->tenth_marksheet)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->twelfth_marksheet) && $writer->writerDocument->twelfth_marksheet)
                    <div class="col-sm-3">
                        <div class="custom-file-upload">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->twelfth_marksheet)}}" class="attachment-title">12<sup>th</sup> Marksheet</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->twelfth_marksheet)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->degree_marksheet) && $writer->writerDocument->degree_marksheet)
                    <div class="col-sm-3">
                        <div class="custom-file-upload mt-3">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->degree_marksheet)}}" class="attachment-title">Degree Marksheet</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->degree_marksheet)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                    @if(isset($writer->writerDocument) && isset($writer->writerDocument->college_transcript) && $writer->writerDocument->college_transcript)
                    <div class="col-sm-3">
                        <div class="custom-file-upload mt-3">
                            <div class="attachments-container">
                                <div class="attachment-box ripple-effect">
                                    <a  target="_blank" href="{{Storage::url($writer->writerDocument->college_transcript)}}" class="attachment-title">College Transcript</a>
                                    <a target="_blank" class="btn btn-sm btn-secondary text-white mr-2" href="{{Storage::url($writer->writerDocument->college_transcript)}}"><span class="fa fa-eye"></span> View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </section>
</div>


<div class="modal fade in verifyModal" id="verifyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <form method="POST" action="/admin/writers/{{$writer->id}}/verify"  enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Verify Writer</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @csrf
                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-xl-12 col-md-12">
                            <label>Select Writer Quality <span style="color: red;">*</span></label>
                            <select class="form-control" name="quality" required>
                                <option value="">Select Quality</option>
                                <option>Standard</option>
                                <option>Premium</option>
                                <option>Platinum</option>
                            </select>
                        </div>
                    </div>
                    <!-- <div class="row form-group">
                        <div class="col-xl-12 col-md-12">
                            <label>Rate<span style="color: red;">*</span></label>
                            <input type="text" name="per_page_rate" pattern="^[0-9]\d*(\.\d+)?$" class="form-control" placeholder="Enter writer rate" required>
                        </div>
                    </div> -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default bg-secondary text-white" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Verify</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')

@endsection